export const ROLES = {
  DEVELOPER: 'developer',
  FINANCIER: 'financier',
  ADMIN: 'admin',
  USER: 'user'
};

export const PRIVILEGED_ROLES = [ROLES.DEVELOPER, ROLES.FINANCIER, ROLES.ADMIN];

export const PERMISSIONS = {
  MANAGE_INCOME: [...PRIVILEGED_ROLES],
  MANAGE_EXPENSE: [...PRIVILEGED_ROLES],
  ACCESS_LOGS: [ROLES.DEVELOPER, ROLES.FINANCIER],
  DELETE_INCOME: [ROLES.DEVELOPER, ROLES.FINANCIER],
  DELETE_EXPENSE: [ROLES.DEVELOPER, ROLES.FINANCIER],
  MANAGE_USERS: [ROLES.DEVELOPER]
};